spring.data.mongodb.uri=mongodb://localhost:27017/biblioteca
spring.thymeleaf.cache=false
server.port=8080
logging.level.root=INFO
logging.level.com.biblioteca=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
